local Widgets = {
    -- example_widget = {
    --     name = "example_widget";
    --     widget =
    --         DockWidgetPluginGuiInfo.new(
    --             Enum.InitialDockState.Float, -- Initial Dock State
    --             false, -- Initially enabled
    --             false, -- Override with initially enabled value
    --             0, -- Floating X Size
    --             0, -- Floating Y Size
    --             0, -- Min Width
    --             0 -- Min Height
    --         );
    -- };
}

return Widgets